### ISSUE TITLE
有人适配安卓9的吗？

### ISSUE THREAD

**Issue by longhuan1999** [dabao1955/KernelSU_General_porting_guide_wiki#2]

**Comment by longhuan1999** [comment]
这是我的解决方案：https://github.com/tiann/KernelSU/discussions/956#discussioncomment-7031296
~目前我做出的修改的稳定性和兼容性还不确定~

**Comment by dabao1955** [comment]
用软连接行吗？例如将/sbin/init连接到/init
________________________________

**Comment by dabao1955** [comment]
> 这是我的解决方案：[tiann/KernelSU#956 (comment)](https://github.com/tiann/KernelSU/discussions/956#discussioncomment-7031296) 目前我做出的修改的稳定性和兼容性还不确定

[坐等大佬提交pr ( ](https://github.com/dabao1955/KernelSU_General_porting_guide_wiki/blob/main/Bug%E4%BF%AE%E5%A4%8D.md)
